import { useEffect, useState } from 'react';
import { ShoppingCart, RefreshCw, Plus } from 'lucide-react';
import AppShell from '../components/AppShell';
import Modal from '../components/Modal';
import api from '../services/api';
import Toast from '../components/Toast';

export default function Orders() {
	const [orders, setOrders] = useState([]); const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]); const [toast, setToast] = useState(''); const [create, setCreate] = useState(false);
	const load = () => { api.get('/orders').then(r => setOrders(r.data)); api.get('/customers').then(r => setCustomers(r.data)); api.get('/stock/summary').then(r => setProducts(r.data)); };
	useEffect(load, []);
	const update = async (id, status) => { try { await api.patch(`/orders/${id}/status`, { status }); load(); setToast('Order status updated'); setTimeout(() => setToast(''), 2000); } catch (e) { setToast(e.response?.data?.message || 'Unable to update'); } };
	const submit = async e => { e.preventDefault(); const form = new FormData(e.target); try { await api.post('/orders', { customer: form.get('customer'), items: [{ product: form.get('product'), quantity: Number(form.get('quantity')) }], couponCode: form.get('couponCode') || undefined }); setCreate(false); load(); setToast('Order created'); setTimeout(() => setToast(''), 2000); } catch (e) { setToast(e.response?.data?.message || 'Unable to create order'); } };
	return <AppShell title="Orders" eyebrow="Order management"><div className="page-intro"><p>Monitor fulfillment from payment to completion.</p><div className="button-group"><button className="secondary-btn" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="primary-btn" onClick={() => setCreate(true)}><Plus size={16}/> New order</button></div></div><section className="panel list-panel"><div className="panel-head"><div><h2>All orders</h2><p>{orders.length} total orders</p></div><ShoppingCart size={19} className="muted"/></div><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.length ? orders.map(o => <tr key={o._id}><td className="strong">{o.orderNumber}</td><td><strong>{o.customer?.name}</strong><small className="table-sub">{o.customer?.email}</small></td><td>{o.items?.length || 0} items</td><td className="strong">${Number(o.total || 0).toFixed(2)}</td><td><select className={`status-select ${o.status}`} value={o.status} onChange={e => update(o._id, e.target.value)}><option>pending</option><option>processing</option><option>shipped</option><option>completed</option><option>cancelled</option></select></td></tr>) : <tr><td colSpan="5" className="empty">No orders yet.</td></tr>}</tbody></table></div></section>{create && <Modal title="Create an order" onClose={() => setCreate(false)}><form className="modal-form" onSubmit={submit}><label>Customer<select name="customer" required>{customers.map(c => <option value={c._id} key={c._id}>{c.name} - {c.email}</option>)}</select></label><label>Product<select name="product" required>{products.map(p => <option value={p._id} key={p._id}>{p.name} ({p.stock} in stock)</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label>Coupon code<input name="couponCode" placeholder="Optional"/></label><button className="primary-btn wide">Create order</button></form></Modal>}<Toast message={toast}/></AppShell>;
}
